### PR TITLE
tape instead mocha

### PR DESCRIPTION
**Pull request by fanatid**
Related: #3

### CODE REVIEW

**Comment by fanatid** [comment]
fails on node 0.10, because `Buffer.compare`
@dcousens what you prefer: polyfill (https://www.npmjs.com/package/buffer-compare) or drop 0.10?

**Comment by dcousens** [comment]
LGTM,  @fanatid can you investigate why Travis failed?

**Comment by fanatid** [comment]
@dcousens as I already said, because node v0.10 doesn't has `compare`

**Comment by fanatid** [comment]
https://github.com/bitcoinjs/bip69/blob/e632fb9f91fe0cc6c31b2110292231d80636c5fe/index.js#L12

**Comment by dcousens** [comment]
Sorry @fanatid, somehow didn't see your comment.

Hmph,  maybe drop `0.10` support and not in the README then?

**Comment by fanatid** [comment]
I'm ok with dropping 0.10 (and even 0.12)
feross/buffer that used as buffer shim in browserify already has `compare`
on other hand buffer-compare is not bigger package
I don't know..

**Comment by dcousens** [comment]
:shrug:

I don't think we should drop `0.12` yet.

**Comment by fanatid** [comment]
No, I meant that I personally ok with dropping even 0.12, not that this package should drop 0.12

**Comment by fanatid** [comment]
How about throw a coin? :laughing: 

``` js
> ['y','n'][Math.round(Math.random())]
```

**Pull request merged**
